/*
Problem statement link - https://www.hackerrank.com/contests/projecteuler/challenges/euler012
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?
*/

import java.util.*;
public class TriangularNumberFactors {
    static int getFirstMaximumDivisors(int K) {
        int numWithMaxDivisors=0;
        int num=0;
        for(int i=1; i<=1000; i++) {
            num=num+i;
            int numDivisors=0;
            for(int k=1; k<=num; k++) {
                if(num%k==0) {
                    numDivisors++;
                }
            }
            if(numDivisors>K) {
                numWithMaxDivisors=num;
                break;
            }
       }//for loop ends...
       return numWithMaxDivisors;
    }

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        System.out.print("Enter no of divisors : ");
        int divis = sc.nextInt();

        System.out.println("\nFirst Number with divisors greater than " + divis + " is : " + getFirstMaximumDivisors(divis));
    }
}
